auto: true

markdown: kramdown

highlighter: 'rouge'
#paginate: 8
permalink: /:title

title:            "南丞嘚吧嘚"
tagline:          "南丞的个人博客"
description:      "听南丞嘚吧技术那些事"
url:  http://friday-go.cc
feed: /atom.xml
author:
  name:           南丞
  url:            http://friday-go.cc
author_info: <a href="http://friday-go.cc/aboutme.html">南丞_</a>
