auto: true

markdown: kramdown

highlighter: 'rouge'
# permalink: /:title
paginate: 5
paginatepath: ['topics/study/page/:num','topics/life/page/:num']
# Setup
title:            "南丞嘚吧嘚"
tagline:          "南丞的个人博客"
description:      "听南丞嘚吧技术那些事"
url:  http://friday-go.cc
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           南丞
  url:            http://friday-go.cc
author_info: <a href="http://friday-go.cc/aboutme.html">南丞_</a>

plugins:
  - jekyll-feed



logo:             favicon.png
lang:             zh-CN
keywords:         www.friday-go.cc, friday-go.cc, friday-go, 南丞嘚吧嘚, 南丞_,Neroxiezi, 博客, Q哥, Neroxiezi的个人博客, Neroxiezi博客

disqus:
  shortname:      南丞
# Custom vars
version:            1.0
sidebar_home_link:  true
github:
  repo:             https://github.com/Neroxiezi